language: objective-c
rvm: 1.9.3
before_install: 
 - "gem update cocoapods"
script: xctool -workspace GrowingTextViewWithAutoLayout.xcworkspace -scheme "GrowingTextViewWithAutoLayout" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO